### ISSUE TITLE
missing component libraries

### ISSUE THREAD

**Issue by woodsmoke** [T3P3/Duet#3]
Where does one get hold of special.lib component library in order to properly open the Duet0.85.sch schematic?

**Comment by T3P3** [comment]
Hi woodsmoke, I guess its a KiCAD library as all the custom parts for the board are in the FE.lib (and should be cached in  Duet0.85-cache.lib as well).
Have you tried looking in the KiCAD install path/share/Library for special.lib? Alternatively you can remove it from the list of libraries associated with the project within eschema using the library editor.

Tony

**Comment by woodsmoke** [comment]
KiCAD received a rather thorough overhaul recently. Library files are all .pretty now I think. I'll try some older versions. Thanks.
