### ISSUE TITLE
Adapting Duet Wifi design for a Teensy 3.6 based controller board

### ISSUE THREAD

**Issue by Flydroid** [T3P3/Duet#4]
Hi Tony,

I'm currently designing a 3D printer controller Board which is based on the[ Teensy 3.6.](https://www.pjrc.com/teensy/techspecs.html). 

For my motivation, i have to say that there isn't a 3d printer controller for the Teensy yet and the new TMC2130 haven't been used with all it s features.  The board should follow the ramps principle, you plug in the microcontroller board and the stepper drivers, here the Teensy 3.6 and the TMC2130 SilentStepSticks.
My current featureset: 
![teensy3d](https://cloud.githubusercontent.com/assets/6762933/22665337/bb155730-ecb4-11e6-9c72-1986d020d476.jpg)

On the software side there are some developments for Marlin on Teensy 3.6 but dc42 also [said](http://forums.reprap.org/read.php?13,711399) that a port of Raprap Firmware HAL CoreNG might be doable. 

I really like the feature set of the  DuetWifi, as it is appropriate to the current 32bit mcus. 
You have published the DuetWifi hardware  files under the Cern OHL 1.2.  I've read the License and  howto from cern. but I'm inexperienced in the open hardware sector.

Would it be possible to base some of my schematics (mosfet endstop) on the duetwifi when giving the appropriate credit following the Cern OHL v1.2? And of course releasing the source on Github. 

Best Regards 
Jonathan

**Comment by T3P3** [comment]
Hi Jonathan

That looks interesting and I saw the thread you linked to. If you port CoreNG to Teensy you then get to benefit from the rest of the RepRapFirmware which has a bunch of nice developments so well worth it.

Regarding the license question you are free to use the DuetWifi hardware design under the terms of the CERN OHL. In summary that means your new project should also be licensed under CERN OHL and the source files shared freely.

HTH, Tony

**Comment by Flydroid** [comment]
Hi Tony,

That's great to hear. I will keep you updated!

I do have three questions about the duat wifi design:
- Why did you choose to use the 74HC125 spi buffer?
- What is the purpose of the caps (C91 - C94) beside de mosfets?
- Why didn't you use an extra diode to protect the endstop inputs in addition to the 10k resistor?

Best Regards
Jonathan

**Comment by Yahchaan** [comment]
Did you look at the Trinamic TRAMS board SPI only? (On a MEGA) It can maybe help give direction.

**Comment by Yahchaan** [comment]
You can download the Eagle files
https://github.com/trinamic/TRAMS

**Comment by Yahchaan** [comment]
Did you do anything more? I cannot program, only do good PCB layout and need input - for I like the teensy

**Comment by Flydroid** [comment]
Unfortunately I haven't been able to continue in the last months. Maybe
later this year.



Yahchaan <notifications@github.com> schrieb am Di., 10. Juli 2018, 17:05:
