### ISSUE TITLE
"Mechanical" Drawings

### ISSUE THREAD

**Issue by Andy-ABTec** [T3P3/Duet#6]
Hi, is there a mechanical drawing available for the Duet 2?

I'm after board dimensions, mounting hole, ethernet connector and other opening positions to aid in case design.

Had a rummage through the code but couldn't spot anything...

Many thanks!

**Comment by theopensourcerer** [comment]
I guess you will need KiCAD. Load the designs from the repository and then you can examine, measure and even print the PCB layout.

Probably from here: https://github.com/T3P3/Duet/tree/master/Duet2/Duet2v1.04

**Comment by T3P3** [comment]
All our documentation is on Dozuki. Have a look here:
https://duet3d.dozuki.com/Wiki/Mounting_and_cooling_the_board
There are also 3D models linked from that page.

**Comment by Andy-ABTec** [comment]
Thanks guys, sorry to have pestered...
